export default {
    'x-red': 'var(--colors-red)',
    'x-gold': 'var(--colors-gold)',
    'x-sky': 'var(--colors-sky)',
    'x-sky-darker': 'var(--colors-sky-darker)',
    'x-darkNight': 'var(--colors-darkNight)',
    'x-twilight': 'var(--colors-twilight)',
    'x-tiffany': 'var(--colors-tiffany)',
    'x-green': 'var(--colors-green)',
    'x-white': 'var(--colors-white)',
    'x-snow': 'var(--colors-snow)',
    colorPrimary: '#2563EB',
    regalBlue: 'rgba(19, 19, 44, 0.9)',
    cText: 'var(--colors-cText)',
    cTextHover: 'var(--colors-cTextHover)',
    skyblue: 'var(--skyblue)',
    'space-blue': 'var(--space-blue)',
    // blue800: '#252e43',
    darkblue: 'var(--darkblue)',
    'global-bg': 'var(--colors-global-bg)',
    'global-2-bg': 'var(--colors-global-2-bg)',
    'global-3-bg': 'var(--colors-global-3-bg)',
    'global-bg-regal': 'var(--colors-global-bg-regal)',
    // navLink
    navLink: 'var(--colors-navLink)',
    'navLink-active': 'var(--colors-navLink-active)',
}
