FROM --platform=linux/amd64 node:16-alpine AS builder

WORKDIR /kzen


# build the project locally
#then copy the dist folder to the image
COPY ./dist ./dist

RUN npm install -g serve

EXPOSE 9008

CMD ["serve", "-s", "dist", "-l", "9008"]
