version: '3.8'
networks:
    kzen-client:
        name: kzen-client
services:
    kzen:
        container_name: kzen-container
        build: .
        ports:
            - '9008:80'
            - '443:443'
            - '446:446'
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - /etc/letsencrypt:/etc/letsencrypt:ro
        networks:
            - kzen-client
        restart: unless-stopped
